cookbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('recipes.urls'), name='recipe_urls'),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

recipes/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('like/<slug:slug>', views.RecipeLike.as_view(), name='recipe_like'),
    path('recipes/add', views.AddRecipe.as_view(), name='add_recipe'),
    path('recipes/profile', views.Profile.as_view(), name='profile'),
    path('recipes/<int:pk>/update/', views.EditRecipe.as_view(), name='edit_recipe'),
    path('recipes/<int:pk>/delete/', views.DeleteRecipe.as_view(), name='delete_recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse

# Create your models here.


class Recipe(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipe_post')
    image = CloudinaryField('image', default='placeholder', blank=True)
    intro = models.TextField(blank=True)
    ingredients = models.TextField()
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
        User, related_name='recipe_like', blank=True)
    favorite = models.ManyToManyField(
        User, related_name='recipe_favorite', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()
    
    def get_absolute_url(self):
        return reverse('recipe_detail', args=[self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

recipes/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

recipes/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Recipe
from .forms import CommentForm

# Create your views here.


class RecipeList(generic.ListView):
    model = Recipe
    template_name = 'index.html'
    paginate_by = 6
    ordering = ['-created_on']


class RecipeDetail(View):

    def get(self, request, slug, *args, **kwargs):
        recipe = get_object_or_404(Recipe, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm(),
            },
        )

    def post(self, request, slug, *args, **kwargs):

        recipe = get_object_or_404(Recipe, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = recipe
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": True,
                "comment_form": comment_form,
                "liked": liked
            },
        )

class RecipeLike(View):
    
    def post(self, request, slug, *args, **kwargs):
        recipe = get_object_or_404(Recipe, slug=slug)
        if recipe.likes.filter(id=request.user.id).exists():
            recipe.likes.remove(request.user)
        else:
            recipe.likes.add(request.user)

        return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


class AddRecipe(generic.CreateView):
    model = Recipe
    template_name = 'add_recipe.html'
    fields = ['title', 'slug', 'image', 'intro', 'ingredients', 'content']
    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class EditRecipe(generic.UpdateView):
    model = Recipe
    template_name = 'edit_recipe.html'
    fields = ['title', 'slug', 'image', 'intro', 'ingredients', 'content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        recipe = self.get_object()
        if self.request.user == recipe.author:
            return True
        return False


class DeleteRecipe(generic.DeleteView):
    model = Recipe
    template_name = 'recipe_confirm_delete.html'
    success_url = '/'

    def test_func(self):
        recipe = self.get_object()
        if self.request.user == recipe.author:
            return True
        return False


class Profile(generic.ListView):
    model = Recipe
    template_name = 'profile.html'
    paginate_by = 6

templates/add_recipe.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add Recipe</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Cookbook</title>
</head>

<body class="d-flex flex-column h-100 main-bg">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Cookbook</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_recipe' %}">Add Recipe</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        {% endblock content %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous">
    </script>
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3500);
    </script>
</body>

</html>

templates/edit_recipe.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit Recipe</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.image.url %}
                                <img class="card-img-top"
                                    src="">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ recipe.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="recipe-link">
                                <h2 class="card-title">{{ recipe.title }}</h2>
                                <p class="card-text">{{ recipe.intro }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ recipe.created_on}} <i class="far fa-heart"></i>
                                {{ recipe.number_of_likes }} </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1>{{ user.username }}</h1>
{% if recipe.author == user %}
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqtpa3fvo/image/upload/v1663454046/cld-sample-4.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ recipe.image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ recipe.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="recipe-link">
                                <h2 class="card-title">{{ recipe.title }}</h2>
                                <p class="card-text">{{ recipe.intro }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ recipe.created_on}} <i class="far fa-heart"></i>
                                {{ recipe.number_of_likes }} </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
{% endif %}
{% endif %}
{% endblock content %}

templates/recipe_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Recipe</legend>
                <h2>Are you sure you want to delete this recipe "{{ recipe.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'recipe_detail' recipe.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/recipe_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ recipe.title }}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">{{ recipe.author }} | {{ recipe.created_on }}</div>
                </header>
                <!-- Preview image figure-->
                {% if "placeholder" in recipe.image.url %}
                <figure class="mb-4"><img class="img-fluid rounded"
                        src="https://res.cloudinary.com/dqtpa3fvo/image/upload/v1663454046/cld-sample-4.jpg" alt="..." /></figure>
                {% else %}
                <figure class="mb-4"></figure><img class="img-fluid rounded" src=" {{ recipe.image.url }}"></figure>
                {% endif %}
                <!-- Post content-->
                <section class="mb-5">
                    <p>
                        <strong>
                            {{ recipe.intro | safe }}
                        </strong>
                    </p>
                    <p>
                        {{ recipe.ingredients | safe }}
                    </p>
                    <p>
                        {{ recipe.content | safe }}
                    </p>
                    {% if recipe.author == user %}
                    <a class="btn btn-secondary btn-sm" href="{% url 'edit_recipe' recipe.pk %}"> Edit </a>
                    <a class="btn btn-danger btn-sm" href="{% url 'delete_recipe' recipe.pk %}"> Delete </a>
                    {% endif %}
                </section>
            </article>
        </div>
    </div>


    <div class="row">

        <div class="col-1">
            <strong>
                {% if user.is_authenticated %}
                <form class="d-inline" action="{% url 'recipe_like' recipe.slug %}" method="POST">
                    {% csrf_token %}
                    {% if liked %}
                    <button type="submit" name="recipe_id" value="{{recipe.slug}}" class="btn-like"><i
                            class="fas fa-heart"></i></button>
                    {% else %}
                    <button type="submit" name="recipe_id" value="{{recipe.slug}}" class="btn-like"><i
                            class="far fa-heart"></i></button>
                    {% endif %}
                </form>
                {% else %}
                <span class="text-secondary"><i class="far fa-heart"></i></span>
                {% endif %}
                <span class="text-secondary">{{ recipe.number_of_likes }} </span>
            </strong>
        </div>
        <div class="col-1">
            {% with comments.count as total_comments %}
            <strong class="text-secondary"><i class="far fa-comments"></i>
                {{ total_comments }}</strong>
            {% endwith %}
        </div>
    </div>


    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">

                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">

                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}